version: '2'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: docker
      FORMATION: web=1
    ports:
      - 3000:3000
    volumes:
      - .:/opt/rails
    links:
      - redis
      - db
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mdillon/postgis:9.6
    ports:
      - 5432:5432
