version: '3'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
